### ISSUE TITLE
Compiled Tinke.exe in 2.0 runtime version and not assembled with plugins in 4.0 framework

### ISSUE THREAD

**Issue by MetLob** [pleonex/tinke#25]
in *Project property* target framework value is **3.5** and .bat script use only **compilator** ver 4.0

**Comment by pleonex** [comment]
I will update the build scripts and project files to use **.NET Framework 3.5** because:

* [Microsoft is not longer supporting](https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/) .NET Framework 4.0, 4.5 and 4.5.1. They only support 3.5, 4.5.2, 4.6 and higher.
* Although [mono supports .NET Framework 4.6](www.mono-project.com/docs/about-mono/compatibility/) I cannot see that option in the project properties from monodevelop (the IDE for C# in Linux).
* .NET Framework is the only version supported in Windows XP and I think there are people using that OS still.

**Comment by pleonex** [comment]
I have decided to upgrade to **.NET Framework 4.5** because:

* [mono has dropped support of old .NET Frameworks](http://www.mono-project.com/docs/about-mono/releases/4.0.0/#dropped-support-for-old-frameworks). This means that it can only compiled with .NET Framework 4.5 but it can run old apps.
* Windows XP is not longer supported by Microsoft so it makes no sense to keep 3.5 just for an unsopported user. Also, there are more user using mono for Linux/MacOS than Windows XP.
* By compiling with .NET Framework 4.5 on mono it fixes magically #10.
