### ISSUE TITLE
Why Ekona and All Plugins Framework versions changed to 4.5?

### ISSUE THREAD

**Issue by MetLob** [pleonex/tinke#37]
1) Plugins Framework versions can be equal to 4.5. But his updates will be working only with new version of Tinke in 4.5 .NET
2) Ekona? All my earlest plugins in 3.5 .NET don't works, because they use Ekona.
3) DSDecmp just as Ekona

My visions of the good issue:
Tinke: 4.5 or hightest with time
Ekona, DSDecmp: only 3.5 for compatible all developers (may be I is one?)
Plugins: 3.5 as base for compatible with a early Tinke version, but can hightest if necessary (new features of new versions).

**Comment by pleonex** [comment]
Hi,
I decided to upgrade to .NET Framework 4.5 in the issue #25. You can find my _arguments_ in this [comment](https://github.com/pleonex/tinke/issues/25#issuecomment-189886848). The key point is that this is necessary to support Linux and Mac OS X users because mono (the .NET runtime for this operative systems) dropped support for previous .NET versions. Can you upgrade your plugins to 4.5? I think you just need to recompile them with that version. I can help you if you need.

**Comment by MetLob** [comment]
Ok. I understand you.
