### ISSUE TITLE
Run it on linux

### ISSUE THREAD

**Issue by SaymoNDev** [pleonex/tinke#49]
How to run it on linux?

**Comment by Mrnumbers9** [comment]
Why closed?

**Comment by Mrnumbers9** [comment]
How did you run it

**Comment by MrJPGames** [comment]
It's a windows app, it's not meant to run on Linux, and unless you use a VM or maybe it works in wine it will not work on Linux.
It's made with Visual Studio which is a Microsoft application for making Windows apps.

**Comment by pleonex** [comment]
Actually yes, it works on Linux because my computer has only a Linux distro OS :)
In fact, I didn't use Visual Studio but Monodevelop to create it.

To run on Linux or Mac OS you need to install mono. To install it you can follow the instructions from their website: http://www.mono-project.com/download/
Then, open a terminal, go to the folder of Tinke and run it with:
```
mono Tinke.exe
```

It will works exactly the same as in Windows does :)

**Comment by Mrnumbers9** [comment]
ah that explains a lot
